// apps/web/src/routes/[locale]/problems/+page.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { t } from "svelte-i18n";
  import ProblemsTabs from "$lib/components/ProblemsTabs.svelte";

  let { data } = $props();
  let locale = $derived(($page.params as { locale: string }).locale);
</script>

<div class="space-y-6">
  <h2 class="font-[family-name:var(--font-display)] text-3xl">{$t("navigation.problems")}</h2>

  <ProblemsTabs
    editableProblems={data.editableProblems}
    publicProblems={data.publicProblems}
    showCreate={data.showCreate}
    {locale}
  />
</div>

// apps/web/src/app/[locale]/problems/page.tsx
import { getTranslations, setRequestLocale } from "next-intl/server";
import { headers } from "next/headers";

import { ProblemsTabs } from "@/components/problems-tabs";
import { auth } from "@/lib/auth";
import { listEditableProblems, listProblemCards } from "@/lib/server/read-model";

export const dynamic = "force-dynamic";

export default async function ProblemsPage({
  params
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);
  const tNav = await getTranslations("navigation");

  const session = await auth.api.getSession({ headers: await headers() });
  const userId = session?.user.id ?? null;

  const [publicProblems, editableProblems] = await Promise.all([
    listProblemCards(),
    userId ? listEditableProblems(userId) : Promise.resolve(null)
  ]);

  return (
    <div className="space-y-6">
      <h2 className="font-[family-name:var(--font-display)] text-3xl">{tNav("problems")}</h2>

      <ProblemsTabs
        editableProblems={editableProblems}
        publicProblems={publicProblems}
        showCreate={!!userId}
      />
    </div>
  );
}
