// apps/web/src/lib/components/CourseProblemShelf.svelte
<script lang="ts">
  import { t } from "svelte-i18n";
  import type { CourseProblemCatalogEntry } from "$lib/server/read-model";

  interface Props {
    courseSlug: string;
    locale: string;
    problems: CourseProblemCatalogEntry[];
  }

  let { courseSlug, locale, problems }: Props = $props();
</script>

<section
  class="rounded-[2rem] border border-[color:var(--color-border)] bg-white/70 px-5 py-5"
>
  <div class="flex items-center justify-between gap-4">
    <div>
      <p class="text-sm uppercase tracking-[0.18em] text-[color:var(--color-muted)]">
        {$t("courseDetail.problemShelf")}
      </p>
      <h3 class="mt-1 text-2xl font-semibold">
        {$t("courseDetail.problemShelfSubtitle")}
      </h3>
    </div>
    <span
      class="rounded-full border border-[color:var(--color-border)] px-3 py-1 text-xs font-medium"
    >
      {problems.length} {$t("courseDetail.linkedProblems")}
    </span>
  </div>
  <div class="mt-5 grid gap-3">
    {#each problems as problem (problem.slug)}
      <a
        class="rounded-[1.5rem] border border-[color:var(--color-border)] bg-white/70 px-4 py-4 transition hover:-translate-y-0.5"
        href="/{locale}/problems/{problem.slug}?course={courseSlug}"
      >
        <div class="flex items-center justify-between gap-4">
          <div>
            <p class="text-lg font-semibold">{problem.title}</p>
            <p class="mt-2 text-sm leading-7 text-[color:var(--color-muted)]">
              {problem.summary}
            </p>
          </div>
          <div class="text-right">
            <span
              class="rounded-full border border-[color:var(--color-border)] px-3 py-1 text-xs font-medium"
            >
              {problem.visibility}
            </span>
            <p class="mt-2 text-sm text-[color:var(--color-muted)]">
              {$t("courseDetail.by")} {problem.authorHandle}
            </p>
          </div>
        </div>
      </a>
    {/each}
  </div>
</section>

// apps/web/src/components/course-problem-shelf.tsx
import Link from "next/link";

import { getLocale, getTranslations } from "next-intl/server";

import { shellClassNames } from "@nojv/ui";

import type { CourseProblemCatalogEntry } from "@/lib/server/read-model";

interface CourseProblemShelfProps {
  courseSlug: string;
  problems: CourseProblemCatalogEntry[];
}

export async function CourseProblemShelf({ courseSlug, problems }: CourseProblemShelfProps) {
  const locale = await getLocale();
  const t = await getTranslations("courseDetail");
  return (
    <section className={`${shellClassNames.card} px-5 py-5`}>
      <div className="flex items-center justify-between gap-4">
        <div>
          <p className={shellClassNames.eyebrow}>{t("problemShelf")}</p>
          <h3 className="mt-1 text-2xl font-semibold">
            {t("problemShelfSubtitle")}
          </h3>
        </div>
        <span className={shellClassNames.badge}>{problems.length} {t("linkedProblems")}</span>
      </div>
      <div className="mt-5 grid gap-3">
        {problems.map((problem) => (
          <Link
            className="rounded-[1.5rem] border border-[color:var(--color-border)] bg-white/70 px-4 py-4 transition hover:-translate-y-0.5"
            href={`/${locale}/problems/${problem.slug}?course=${courseSlug}`}
            key={problem.slug}
          >
            <div className="flex items-center justify-between gap-4">
              <div>
                <p className="text-lg font-semibold">{problem.title}</p>
                <p className="mt-2 text-sm leading-7 text-[color:var(--color-muted)]">
                  {problem.summary}
                </p>
              </div>
              <div className="text-right">
                <span className={shellClassNames.badge}>{problem.visibility}</span>
                <p className="mt-2 text-sm text-[color:var(--color-muted)]">
                  {t("by")} {problem.authorHandle}
                </p>
              </div>
            </div>
          </Link>
        ))}
      </div>
    </section>
  );
}
