// apps/web/src/lib/components/TelemetryProbe.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { CheatingSignal } from "@nojv/domain";
  import { authClient } from "$lib/auth-client";

  interface Props {
    assessment?: CheatingSignal["assessment"];
    contestSlug?: string;
    sessionId: string;
    signalSource: CheatingSignal["source"];
  }

  let { assessment, contestSlug, sessionId, signalSource }: Props = $props();

  onMount(() => {
    let recentSignals: CheatingSignal[] = [];
    let blurCount = 0;

    async function emitSignals(signals: CheatingSignal[]) {
      await fetch("/api/integrity/signals", {
        body: JSON.stringify(signals),
        headers: { "Content-Type": "application/json" },
        method: "POST"
      });
    }

    function bufferSignal(signal: Omit<CheatingSignal, "capturedAt">) {
      const snapshot: CheatingSignal = {
        ...signal,
        capturedAt: new Date().toISOString()
      };
      recentSignals = [...recentSignals, snapshot].slice(-4);
      void emitSignals(recentSignals);
    }

    function onWindowBlur() {
      blurCount += 1;
      bufferSignal({
        assessment,
        confidence: Math.min(0.9, 0.22 + blurCount * 0.14),
        contestSlug,
        payload: { blurCount },
        sessionId,
        source: signalSource,
        type: "focus_loss",
        userId: ""
      });
    }

    function onPaste(event: ClipboardEvent) {
      const pastedText = event.clipboardData?.getData("text") ?? "";
      if (pastedText.length < 24) return;

      bufferSignal({
        assessment,
        confidence: Math.min(0.96, 0.3 + pastedText.length / 600),
        contestSlug,
        payload: { pastedCharacters: pastedText.length },
        sessionId,
        source: signalSource,
        type: "paste_burst",
        userId: ""
      });
    }

    window.addEventListener("blur", onWindowBlur);
    document.addEventListener("paste", onPaste);

    return () => {
      window.removeEventListener("blur", onWindowBlur);
      document.removeEventListener("paste", onPaste);
    };
  });
</script>

// apps/web/src/components/telemetry-probe.tsx
"use client";

import { useEffect, useEffectEvent, useRef } from "react";

import type { CheatingSignal } from "@nojv/domain";

import { authClient } from "@/lib/auth-client";

interface TelemetryProbeProps {
  assessment?: CheatingSignal["assessment"];
  contestSlug?: string | undefined;
  sessionId: string;
  signalSource: CheatingSignal["source"];
}

export function TelemetryProbe({
  assessment,
  contestSlug,
  sessionId,
  signalSource
}: TelemetryProbeProps) {
  const { data: session } = authClient.useSession();
  const userId = session?.user.id ?? "";
  const recentSignalsRef = useRef<CheatingSignal[]>([]);
  const blurCountRef = useRef(0);

  const emitSignals = useEffectEvent(async (signals: CheatingSignal[]) => {
    await fetch("/api/integrity/signals", {
      body: JSON.stringify(signals),
      headers: {
        "Content-Type": "application/json"
      },
      method: "POST"
    });
  });

  const bufferSignal = useEffectEvent((signal: Omit<CheatingSignal, "capturedAt">) => {
    const snapshot: CheatingSignal = {
      ...signal,
      capturedAt: new Date().toISOString()
    };

    recentSignalsRef.current = [...recentSignalsRef.current, snapshot].slice(-4);
    void emitSignals(recentSignalsRef.current);
  });

  useEffect(() => {
    const onWindowBlur = () => {
      blurCountRef.current += 1;

      bufferSignal({
        assessment,
        confidence: Math.min(0.9, 0.22 + blurCountRef.current * 0.14),
        contestSlug,
        payload: {
          blurCount: blurCountRef.current
        },
        sessionId,
        source: signalSource,
        type: "focus_loss",
        userId
      });
    };

    const onPaste = (event: ClipboardEvent) => {
      const pastedText = event.clipboardData?.getData("text") ?? "";

      if (pastedText.length < 24) {
        return;
      }

      bufferSignal({
        assessment,
        confidence: Math.min(0.96, 0.3 + pastedText.length / 600),
        contestSlug,
        payload: {
          pastedCharacters: pastedText.length
        },
        sessionId,
        source: signalSource,
        type: "paste_burst",
        userId
      });
    };

    window.addEventListener("blur", onWindowBlur);
    document.addEventListener("paste", onPaste);

    return () => {
      window.removeEventListener("blur", onWindowBlur);
      document.removeEventListener("paste", onPaste);
    };
  }, [userId, assessment, contestSlug, sessionId, signalSource]);

  return null;
}
