// apps/web/src/routes/courses/+page.svelte
<script lang="ts">
  import { t } from "svelte-i18n";

  let { data } = $props();
</script>

<div class="space-y-6">
  <h2 class="font-[family-name:var(--font-display)] text-3xl">{$t("navigation.courses")}</h2>

  {#if data.courses.length === 0}
    <p class="text-sm text-[color:var(--color-muted)]">{$t("courseDetail.empty")}</p>
  {/if}

  <section class="grid gap-4 lg:grid-cols-2">
    {#each data.courses as course (course.slug)}
      <a
        class="rounded-[2rem] border border-[color:var(--color-border)] bg-white/70 px-6 py-6 transition hover:-translate-y-0.5"
        href="/courses/{course.slug}"
      >
        <div class="flex items-center justify-between gap-4">
          <div>
            <p class="text-sm uppercase tracking-[0.18em] text-[color:var(--color-muted)]">
              {$t("courseDetail.course")}
            </p>
            <h3 class="mt-2 text-2xl font-semibold">{course.title}</h3>
          </div>
          <span
            class="rounded-full border border-[color:var(--color-border)] px-3 py-1 text-xs font-medium"
          >
            {$t("courseDetail.rbacEnabled")}
          </span>
        </div>
        <dl class="mt-5 grid gap-4 sm:grid-cols-2">
          <div>
            <dt class="text-sm text-[color:var(--color-muted)]">{$t("common.members")}</dt>
            <dd class="mt-1 text-lg font-semibold">{course.memberCount}</dd>
          </div>
          <div>
            <dt class="text-sm text-[color:var(--color-muted)]">{$t("common.assessments")}</dt>
            <dd class="mt-1 text-lg font-semibold">{course.assessmentCount}</dd>
          </div>
        </dl>
      </a>
    {/each}
  </section>
</div>

// apps/web/src/app/[locale]/courses/page.tsx
import Link from "next/link";

import { getTranslations, setRequestLocale } from "next-intl/server";
import { shellClassNames } from "@nojv/ui";

import { CourseCreationPanel } from "@/components/course-creation-panel";
import { listCourseCards } from "@/lib/server/read-model";

export const dynamic = "force-dynamic";

export default async function CoursesPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);

  const [tNav, tCourse, tCommon] = await Promise.all([
    getTranslations("navigation"),
    getTranslations("courseDetail"),
    getTranslations("common")
  ]);
  const courses = await listCourseCards();

  return (
    <div className="space-y-6">
      <section className={`${shellClassNames.cardStrong} px-6 py-6 sm:px-8`}>
        <h2 className="font-[family-name:var(--font-display)] text-3xl">
          {tNav("courses")}
        </h2>
      </section>

      <section className="grid gap-4 lg:grid-cols-2">
        <CourseCreationPanel />
        {courses.map((course) => (
          <Link
            className={`${shellClassNames.card} px-6 py-6`}
            href={`/${locale}/courses/${course.slug}`}
            key={course.slug}
          >
            <div className="flex items-center justify-between gap-4">
              <div>
                <p className="text-sm uppercase tracking-[0.18em] text-[color:var(--color-muted)]">
                  {tCourse("course")}
                </p>
                <h3 className="mt-2 text-2xl font-semibold">{course.title}</h3>
              </div>
              <span className={shellClassNames.badge}>{tCourse("rbacEnabled")}</span>
            </div>
            <dl className="mt-5 grid gap-4 sm:grid-cols-2">
              <div>
                <dt className="text-sm text-[color:var(--color-muted)]">{tCommon("members")}</dt>
                <dd className="mt-1 text-lg font-semibold">{course.memberCount}</dd>
              </div>
              <div>
                <dt className="text-sm text-[color:var(--color-muted)]">{tCommon("assessments")}</dt>
                <dd className="mt-1 text-lg font-semibold">{course.assessmentCount}</dd>
              </div>
            </dl>
          </Link>
        ))}
      </section>
    </div>
  );
}
