// apps/web/src/routes/[locale]/courses/[slug]/+page.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { t } from "svelte-i18n";
  import CourseAssessmentBoard from "$lib/components/CourseAssessmentBoard.svelte";
  import CourseProblemShelf from "$lib/components/CourseProblemShelf.svelte";
  import CourseJoinPanel from "$lib/components/CourseJoinPanel.svelte";

  let { data } = $props();
  let locale = $derived(($page.params as { locale: string }).locale);
  let slug = $derived(($page.params as { slug: string }).slug);
  let course = $derived(data.courseData.course);
</script>

<div class="space-y-6">
  <section
    class="rounded-[2rem] border border-[color:var(--color-border)] bg-gradient-to-br from-white/90 to-stone-50/80 px-6 py-8 sm:px-8"
  >
    <div class="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
      <div>
        <div class="flex items-center gap-3">
          <p class="text-sm uppercase tracking-[0.18em] text-[color:var(--color-muted)]">
            {$t("navigation.courses")} / {course.slug}
          </p>
          <a
            class="rounded-full border border-[color:var(--color-border)] px-3 py-1 text-xs font-medium transition hover:-translate-y-0.5"
            href="/{locale}/courses/{slug}/manage"
          >
            Manage &rarr;
          </a>
        </div>
        <h2 class="mt-2 font-[family-name:var(--font-display)] text-4xl">
          {course.title}
        </h2>
        <p class="mt-4 max-w-3xl text-base leading-7 text-[color:var(--color-muted)]">
          {course.description}
        </p>
      </div>
      <div class="grid gap-3 sm:grid-cols-3 lg:grid-cols-1">
        <div
          class="rounded-[2rem] border border-[color:var(--color-border)] bg-white/70 px-4 py-4"
        >
          <p class="text-sm text-[color:var(--color-muted)]">{$t("common.members")}</p>
          <p class="mt-2 text-lg font-semibold">{course.members.length}</p>
        </div>
        <div
          class="rounded-[2rem] border border-[color:var(--color-border)] bg-white/70 px-4 py-4"
        >
          <p class="text-sm text-[color:var(--color-muted)]">{$t("common.assessments")}</p>
          <p class="mt-2 text-lg font-semibold">{course.assessments.length}</p>
        </div>
        <div
          class="rounded-[2rem] border border-[color:var(--color-border)] bg-white/70 px-4 py-4"
        >
          <p class="text-sm text-[color:var(--color-muted)]">{$t("courseDetail.problemPool")}</p>
          <p class="mt-2 text-lg font-semibold">{course.problemSlugs.length}</p>
        </div>
      </div>
    </div>
  </section>

  <section class="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
    <div class="space-y-6">
      <CourseAssessmentBoard assessments={course.assessments} courseSlug={course.slug} {locale} />
      <CourseProblemShelf
        courseSlug={course.slug}
        problems={data.courseData.problems}
        {locale}
      />
    </div>
    <div class="space-y-6">
      <CourseJoinPanel courseSlug={course.slug} joinChannels={course.joinChannels} {locale} />
    </div>
  </section>
</div>

// apps/web/src/app/[locale]/contests/[slug]/page.tsx
import Link from "next/link";
import { notFound } from "next/navigation";

import { type LocaleCode } from "@nojv/domain";
import { getCopy, isLocale } from "@nojv/i18n";
import { shellClassNames } from "@nojv/ui";

import { getContestPageData } from "@/lib/server/read-model";

export const dynamic = "force-dynamic";

export default async function ContestDetailPage({
  params
}: {
  params: Promise<{ locale: string; slug: string }>;
}) {
  const { locale, slug } = await params;
  const currentLocale: LocaleCode = isLocale(locale) ? locale : "zh-TW";
  const labels = getCopy(currentLocale);
  const contest = await getContestPageData(slug);

  if (!contest) {
    notFound();
  }

  return (
    <div className="space-y-6">
      <section className={`${shellClassNames.cardStrong} px-6 py-8 sm:px-8`}>
        <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
          <div>
            <p className={shellClassNames.eyebrow}>
              {labels.navigation.contests} / {contest.slug}
            </p>
            <h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl">
              {contest.title}
            </h2>
            <p className="mt-4 max-w-3xl text-base leading-7 text-[color:var(--color-muted)]">
              {contest.summary}
            </p>
          </div>
          <div className="grid gap-3 sm:grid-cols-2">
            <div className={`${shellClassNames.card} px-4 py-4`}>
              <p className="text-sm text-[color:var(--color-muted)]">Scoreboard</p>
              <p className="mt-2 text-lg font-semibold">
                {contest.frozenScoreboard ? "Frozen" : "Live"}
              </p>
            </div>
            <div className={`${shellClassNames.card} px-4 py-4`}>
              <p className="text-sm text-[color:var(--color-muted)]">Problems</p>
              <p className="mt-2 text-lg font-semibold">{contest.problems.length}</p>
            </div>
          </div>
        </div>
      </section>

      <section className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
        <div className={`${shellClassNames.card} px-6 py-6`}>
          <div className="flex items-center justify-between gap-4">
            <div>
              <p className={shellClassNames.eyebrow}>Contest problems</p>
              <h3 className={shellClassNames.sectionTitle}>Problems</h3>
            </div>
            <span className={shellClassNames.badge}>{contest.problems.length} problems</span>
          </div>
          <div className="mt-5 space-y-3">
            {contest.problems.map((problem) => (
              <Link
                className="flex items-center justify-between gap-4 rounded-[1.5rem] border border-[color:var(--color-border)] bg-white/70 px-4 py-4 transition hover:-translate-y-0.5"
                href={`/${currentLocale}/problems/${problem.slug}?contest=${contest.slug}`}
                key={problem.slug}
              >
                <div>
                  <p className="text-sm uppercase tracking-[0.18em] text-[color:var(--color-muted)]">
                    {problem.slug}
                  </p>
                  <p className="mt-1 text-lg font-semibold">{problem.title}</p>
                </div>
                <span className={shellClassNames.badge}>{problem.points} pts</span>
              </Link>
            ))}
          </div>
        </div>

        <aside className="space-y-6">
          <section className={`${shellClassNames.card} px-5 py-5`}>
            <p className={shellClassNames.eyebrow}>Timeline</p>
            <div className="mt-4 space-y-3 text-sm leading-7 text-[color:var(--color-muted)]">
              <p>Starts: {new Date(contest.startsAt).toLocaleString()}</p>
              <p>Ends: {new Date(contest.endsAt).toLocaleString()}</p>
              <p>Scoreboard: {contest.frozenScoreboard ? "freeze-aware" : "live-ranked"}</p>
            </div>
          </section>
        </aside>
      </section>
    </div>
  );
}
